matter-labs/zksync-cli

README.md, bin/create.d.ts, bin/create.js, bin/deposit.d.ts, bin/deposit.js, bin/index.js, bin/withdraw.d.ts, bin/withdraw.js, package-lock.json, package.json, src/create.ts, src/deposit.ts, src/index.ts, src/withdraw.ts, tsconfig.json
Adds `deposit` and `withdraw` methods.
=> Deposit + withdraw

bin/deposit.js, package-lock.json, package.json, src/deposit.ts
Added additional question that allows user to select the network.
=> Added support for other networks (mainnet and localnet)

src/confirm-withdraw.ts, src/create.ts
=> adds vyper template

package.json
=> version 0.2.5

.eslintrc, .prettierrc, package-lock.json, package.json, src/analytics.ts, src/confirm-withdraw.ts, src/create.ts, src/deposit.ts, src/help.ts, src/index.ts, src/replace.ts, src/utils.ts, src/withdraw.ts, src/zeek.ts, tsconfig.json
What changed:
- Added `@matterlabs/eslint-config-typescript` and `@matterlabs/prettier-config` packages
- Fixed (silenced some) code style errors
- Migrated all .js files to .ts
- Added `npm run lint` to check for lint errors and warnings
=> chore: add eslint and prettier

.husky/commit-msg, .husky/pre-commit, commitlint.config.js, package-lock.json, package.json
What changed:
- Added commit message validation
- Added pre-commit hook to lint staged files
=> chore: add commitlint, lint staged files

.github/workflows/feature.yml, .github/workflows/pr-validation.yml
What changed:
- Added new workflow file `pr-validation.yml` that runs lint checks
=> chore: add lint check for pr

README.md
* Remove information about global installation of zksync-cli.
* Make it more clear that recommended way to use CLI is via NPX. And installing it globally is not recommended since it may cause more permission issues as well as not receiving all latest updates automatically.
=> chore: improve usage description

README.md
- Add official Links
- Add links to unify
=> feat(docs): add official Links

src/utils/docker.ts
* Use `docker-compose` instead of `docker compose`
* `docker compose` doesn't work on all systems
=> fix: docker compose

README.md, docs/contract-interaction.md, src/commands/contract/common/options.ts, src/commands/contract/read.ts, src/commands/contract/write.ts, src/commands/create/index.ts, src/common/options.ts, src/data/chains.ts
* Update chain names and keys
* Remove redundant command option keys
* Improve command option descriptions
* Updated chains info to keep consistent with other tools
* Updated command options to keep more consistent across all of the commands
N/A
=> fix: update configs

README.md, package-lock.json, package.json, src/commands/bridge/deposit.ts, src/commands/bridge/withdraw-finalize.ts, src/commands/bridge/withdraw.ts, src/commands/contract/read.ts, src/commands/contract/write.ts, src/commands/wallet/balance.ts, src/commands/wallet/transfer.ts, src/common/options.ts, src/utils/helpers.ts
* Update all included modules to latest version
* Have modules up-to-date and fix npm audit warnings
=> fix: update modules and fix option keys

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/config.yml
* Fix dev discussions link
* Previous link had a typo
=> chore: update dev discussion link

README.md
- add YouTube to official links
- add YouTube to official links
=> chore(docs): add YouTube to official links

src/commands/create/groups/contracts.ts, src/commands/create/groups/frontend.ts, src/commands/create/groups/scripting.ts
* Added `create` templates for ethers v6
* Ethers v6 is getting more traction by developers
=> feat: add ethers6 templates

README.md, docs/contract-interaction.md, docs/transaction-info.md, src/commands/contract/utils/helpers.ts, src/commands/transaction/command.ts, src/commands/transaction/index.ts, src/commands/transaction/info.ts, src/common/prompts.ts, src/index.ts, src/utils/formatters.ts
* Added `npx zksync-cli transaction info` command
* To parse transactions from any chain of choice
=> feat: add transaction info command

src/utils/packageManager.ts
* addresses deps installation issue with upgrade by including `--force` 
* Installation fails otherwise for upgradability templates
=> fix: addresses deps installation issue with upgrade

.github/ISSUE_TEMPLATE/config.yml, package-lock.json, package.json
* Bumps zkcli-in-memory dep for rich wallets link fix
* Fix link to docs in issue template
* `dev start` prints a link to the old docs for the rich wallets info
=> Rich wallets broken link

package-lock.json, package.json
Update zkcli-block-explorer dependency.
Because new version has a required fix.
=> fix: update zkcli-block-explorer dependency

package-lock.json, package.json
Update zkcli-dockerized-node module.
Because a new zkcli-dockerized-node module version was released.
=> fix: update zkcli-dockerized-node module

package-lock.json, package.json, src/data/chains.ts
* First thing updated with this PR
* Second thing updated with this PR
* Third thing updated with this PR
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR
=> fix: bump dep of zkcli-anvil-zksync

src/commands/bridge/deposit.ts, src/commands/bridge/withdraw-finalize.ts, src/commands/bridge/withdraw.ts, src/data/chains.ts, src/utils/helpers.ts, src/utils/token.ts, tsconfig.json
* Fixes withdrawal finalization
* updates free nodes
* It did not work and failed
* previous RPC nodes were down
=> fix: address issue with bridging

src/commands/bridge/deposit.ts, src/commands/bridge/withdraw-finalize.ts, src/commands/bridge/withdraw.ts, src/utils/helpers.ts
* address issue with custom rpc use for l1
* It did not work previously due to chainID not being specified for static network
=> fix: address issue with custom rpc

src/commands/bridge/withdraw-finalize.ts
* First thing updated with this PR
* Second thing updated with this PR
* Third thing updated with this PR
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR
=> chore: improve error message
