matter-labs/zksync-cli

src/index.ts

* Fix the localnet network option when overrides not supplied
* Currently, the value `undefined` is being cast as the string `undefined` and will cause network connection errors
Running
```bash
npm run build && npm uninstall -g zksync-cli && npm i -g && \
zksync-cli deposit --l1-rpc-url=http://127.0.0.1:8545
```
resulted in the following (I manually added some `console.log(..)` statements in the `deposit.ts` command:

Fix the localnet network option

---

README.md
src/help.ts

* Fix the inconsistent name for `confirm-withdraw` command
* `README.md` is incorrect and so was the `--help` response
Running
```bash
zksync-cli help
```
outputs

docs: fix incorrect command name for confirming withdrawals

---

.github/CODEOWNERS
.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_report.md
.github/pull_request_template.md
README.md
package-lock.json
package.json

What changed:
- Added CODEOWNERS, CONTRIBUTING.md, issue and PR templates
- Improved README
Proof:
- `node ./bin` works with params:

chore: make repo open-source ready

---

src/commands/create-project.ts
src/commands/withdraw-finalize.ts
src/common/options.ts
src/utils/analytics.ts

* Single-dash short options replaced with double dashed (eg. `-c` -> `--c`)
* Added short options for amount (`--a <amount>`) and recipient (`--to <address>`)
* Set analytics log level to "error"
* Single dash options were not working properly
* Make setting transaction details easier.
* Capture only essential error events in logs.

fix: short options, disable analytics logs

---

src/commands/create/create.ts

* Replaced running raw unix commands like `cd` or `rm` with node.js native methods (from `fs` package)
* Properly handle the case when folder already exists
* Check for yarn installation, before running yarn scripts
* Improved text and colors for all `project create` logs
* To improve cross-platform compatibility
* To prevent potential errors or overwriting during project creation
* To ensure successful script execution without dependency failures
* To enhance user experience with clearer and visually appealing logs

fix: create project works on all systems, properly remove git folder

---

.github/workflows/release.yml

Migration from deprecated self-hosted, ci-runners to matterlabs-ci-runners
We are moving from deprecated runners to stable.

ci: Migration from ci-runner to matterlabs-ci-runner

---

src/commands/create/create.ts

* Remove `.github` folder when cloning repo during `create project`
* To remove repo specific files like: code owners, PR and Issue templates, etc.

fix: remove github folder when cloning template repo

---

src/utils/logger.ts

- Optimize the code to improve scalability and readability.
- Improve code readability and extensibility, making it easier for developers to understand and expand.

chore: optimize logger code readability

---

src/commands/create/groups/scripting.ts
src/commands/create/utils.ts

* Added missing scripting ethers template path
* Handle errors during project creation process
* Scripting ethers template was failing due to missing template path
* Previously, if there was an error during project creation, the spinner would be spinning indefinitely and process would not stop.

fix: handle failing template installation

---

src/commands/bridge/withdraw.ts
src/data/chains.ts

Change L2, L1 and in memory node rpc url in `chains.ts` file to use `127.0.0.1` instead of `localhost`.
Both `bridge withdraw` and `bridge deposit` operations does not work with `zksync-server` running outside docker , particullarly using the command in [zksync-era](https://github.com/matter-labs/zksync-era) because a network error occurs.

Update rpc URLs

---

package-lock.json
package.json
src/commands/dev/config.ts
src/commands/dev/install.ts
src/commands/dev/logs.ts
src/commands/dev/modules/index.ts
src/commands/dev/start.ts
src/commands/dev/update.ts

* Update block explorer module to support in-memory node
* Update dockerized node with improved contracts deployment waiting loader
* Change all command logs to include `npx`
* Install order in correct order
* Include `npx` in all command logs as it is recommended way to use `zksync-cli`
* Install firstly those modules that can be started at the same time with the node, then the rest

feat: update modules, command log changes, installation in correct order

---

src/commands/create/groups/contracts.ts

* Hide private key input in `create` command
* Use a single repo for all contract templates
* Hide private key input for privacy/security reason
* For consistency with other templates all contracts were moved to a [single repo](https://github.com/matter-labs/zksync-contract-templates/)

fix: hide private key input, use combined templates repo

---

src/data/chains.ts

* Add zkSync Sepolia Testnet
* Since Goerli testnet is being deprecated and Sepolia becomes the main zkSync Testnet

feat: add zksync sepolia testnet

---

README.md
docs/contract-interaction.md
src/data/chains.ts

* Replaced Goerli mentions in docs with Sepolia
* Because zkSync Goerli Testnet is being deprecated
N/A

chore(docs): update testnet docs

---

README.md
docs/contract-interaction.md
src/commands/contract/encode.ts
src/commands/contract/index.ts
src/commands/contract/read.ts
src/commands/contract/utils/helpers.ts
src/commands/contract/write.ts

* Added `npx zksync-cli contract encode` command
* To provide possibility of encoding contract method and arguments into raw hex format
* N/A

feat: add contract encode command

---

package-lock.json
package.json
src/commands/contract/utils/helpers.ts
src/commands/contract/utils/proxy.ts
src/utils/constants.ts
src/utils/helpers.ts
src/utils/token.ts

* Uninstall zksync-web3 package
* Install and use zksync-ethers instead
* zksync-web3 package is deprecated in favor of zksync-ethers
N/A

fix: use zksync-ethers instead of zksync-web3 package

---

README.md
src/commands/create/groups/scripting.ts

This PR adds web3js templates to the CLI
[CLI PR](https://github.com/matter-labs/zksync-cli/pull/121)
[Templates PR](https://github.com/matter-labs/zksync-scripting-templates/pull/4)
[web3-zksync-plugin](https://github.com/web3/web3-plugin-zksync)
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR
- This PR has to be merged [AFTER the template PR](https://github.com/matter-labs/zksync-scripting-templates/pull/4)

feat: add web3js templates

---

src/commands/transaction/info.ts
src/utils/constants.ts

* Fix the path error for importing constants from zksync-ethers, due to updates in zksync-ethers causing zksync-cli to fail to run after installation.
* Since zksync-ethers in version 0.5.6 changed the tsconfig's rootDir from `.` to `./src`, it altered the output directory structure, leading to errors when zksync-cli imports constants from zksync-ethers; to prevent future issues caused by dependency project directory adjustments, it's necessary to change the import method:
```ts
- import { BOOTLOADER_FORMAL_ADDRESS } from "zksync-ethers/build/src/utils.js";
- BOOTLOADER_FORMAL_ADDRESS;
+ import { utils } from "zksync-ethers";
+ utils.BOOTLOADER_FORMAL_ADDRESS;
```
[zksync-ethers in version 0.5.6 changed the tsconfig's rootDir from `.` to …

fix: import zksync-ethers constants path error (zksync-ethers >= v0.5.6)

---

src/commands/create/groups/frontend.ts

* Added svelte frontend templates option in create command
* Svelte frontend templates were added in templates repo, but weren't in cli

feat: add svelte frontend templates for create command

---

src/commands/create/groups/quickstart.ts
src/commands/create/index.ts

Opening this as a DRAFT PR so we can first have a discussion / review and then I may proceed to update the templates from personal repos to official templates repo. 
Some discussion points:
- Previous conversation we discussed "hiding" the quickstart templates from the template option list, do you think this is necessary? 
- Any suggestions on preferred naming convention on templates value. Currently using qs (short for quickstart), followed by guide. For example `qs-testing` for the quickstart testing template. 
Relevant PR: https://github.com/matter-labs/zksync-contract-templates/pull/11
* Adds quickstart templates option
* Easy onboarding for new docs site
* Any …

feat: add quickstart template options

---

src/commands/create/groups/quickstart.ts

Related to: https://github.com/matter-labs/zksync-contract-templates/pull/12
* Updates paths to correctly point to hardhat templates for quickstart
* They are being updated

chore: update paths to reflect qs hardhat paths

---

src/commands/wallet/transfer.ts

* When transferring an ERC20 token, considers the decimals to ensure that the correct amount is sent.
* Ensures `transfer` supports ERC20s with decimals different from the default 18
* Aligns `transfer` with the `balance`, `deposit` and `withdraw` commands
Transaction using native USDC (6 decimals). It correctly sends 0.1 tokens
```
npm run dev -- wallet transfer --token 0x1d17CBcF0D6D143135aE902365D2E5e2A16538D4 --chain zksync-mainnet --recipient 0xD1DF83CA61941dbDf28A212F03E106E3FF00E38e --amount 0.1
Transfer sent:
Transaction hash: 0x615a58c7c8ca9b2e92c364181c075224fd41549f8934b8e1f4fee8a590bc4626
Transaction link: https://explorer.zksync.io/tx/0x615a58c7c8ca9b2e92c364181c075224fd41549f8934b8e1f4fee8a590bc4626
```
* Fixes https://github.com/matter-labs/zksync-cli/issues/143

feat: consider token decimals in transfer

---

src/utils/docker.ts

Fix for https://github.com/matter-labs/zksync-cli/issues/133
Paths for the docker-compose command are wrapped in quotes, which avoids problems if there are spaces in the path.

fix: wrap pathes for docker compose in quotes

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
README.md
docs/contract-interaction.md
docs/transaction-info.md
package.json
src/commands/create/index.ts
src/commands/dev/command.ts
src/commands/dev/restart.ts
src/commands/dev/start.ts
src/commands/dev/stop.ts
src/data/chains.ts

fix: update to ZKsync

---

src/data/chains.ts

* remove goerli from the cli
* chain not supported

chore: rm goerli

---

src/commands/create/groups/contracts.ts
src/commands/create/groups/frontend.ts
src/commands/create/groups/quickstart.ts
src/commands/create/groups/scripting.ts

* removes ethers v5 from commands
* no longer supporting v5

chore: remove ethers v5

---

.github/workflows/pr-validation.yml
.lintstagedrc.yml
cspell-config/cspell-misc.txt
cspell-config/cspell-zksync.txt
cspell.json
package-lock.json
package.json
src/commands/create/index.ts

Add cspell to project. Sets up cspell as part of linstaged.

chore: add cspell to project

---

src/commands/contract/encode.ts
src/commands/contract/read.ts
src/commands/contract/utils/formatters.ts
src/commands/contract/write.ts

For contract commands read/write/encode, the args option does not format and encode array args properly and will error.
This fixes formatting incoming args if they are arrays into a format that will encode properly. Array args can be accepted as a full string with array brackets "[42,77]" or as a string input with comma separated values without the array brackets "42,77".
Fixes #164

fix: parse array args correctly

---

.github/workflows/pr-validation.yml
.github/workflows/release.yml

It's nice to be up-to-date. AFAIK there is no breaking changes between v3 and v4 for both `actions/setup-node` and `actions/checkout` besides using Node.js v20 as the default runtime instead of v16 which Node.js dropped out from their long term support.
https://github.com/actions/setup-node/compare/v3...v4.0.0#diff-1243c5424efaaa19bd8e813c5e6f6da46316e63761421b3e5f5c8ced9a36e6b6R36
https://github.com/actions/checkout/compare/v4.0.0...v4.1.0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R15
Check github workflows

chore: bump github actions

---

README.md
src/commands/create/groups/frontend.ts

* add web3js templates to cli
* Second thing updated with this PR
* Third thing updated with this PR
* Reason why first thing was added to PR
* Reason why second thing was added to PR
* Reason why third thing was added to PR

feat: add web3js to cli

---

src/utils/git.ts

Add get latest commit hash function to the git module.
If module dependencies don't have git release versions, the module still can use commit hashes as a module version. This way, CLI can detect when the module should be updated and will suggest it to the user.

feat: add get latest commit hash function
